# This file is in YAML syntax (see http://www.yaml.org)
#
# The syntax is INDENTATION-SENSITIVE.  Mess it up at your peril!
#
language: java
jdk:
  - oraclejdk7
env:
  global:
    - SONATYPE_USERNAME=joeycoleman
    - secure: "LV3gkLdIXN/W10xeoIZ5lxFbVGeOPjwEvWjYzoCeX/MQrSWiY+oK22mhL1H84RczHHk9jvwlRK9ZEElKOj0vl/ywL/mF7WJgoUIDMUIAQ/jeZsJ7tF4S5o1Drjgwa6dZYLgEkNXWE4cb63vDGUQhRJz3Qq3/fntmvbKL2qCmJcE="
before_install:
  - mvn -version
install:
  - echo "-*- Precompile Core -*-"
  - mvn -B install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
  - echo "-*- Precompile IDE -*-"
  - mvn -B install -f ide/pom.xml -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgit-commit-id.skip=true
script: 
  - echo "-*- Compile Core -*-"
  - mvn -B install
  - echo "-*- Compile IDE -*-"
  - mvn -B install -f ide/pom.xml -Dgit-commit-id.skip=true -Pall-platforms
after_success:
  - "[[ $TRAVIS_BRANCH == \"development\" ]] && { echo \"-*- Deploying snapshots to Sonatype -*-\"; python tools/scripts/addServer.py; mvn deploy --settings ~/.m2/mySettings.xml; };"
